"""Add audio and physical status columns+fields

Revision ID: 078a59516627
Revises: 575705550f21
Create Date: 2025-06-28 18:25:34.493798

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "078a59516627"
down_revision: str | None = "575705550f21"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

status_enum = sa.Enum(
    "Wanted",
    "Have",
    "Ignored",
    "Delete",
    name="book_status",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "books",
        sa.Column(
            "a_status",
            status_enum,
            server_default="Wanted",
            nullable=False,
        ),
    )
    op.add_column(
        "books",
        sa.Column(
            "p_status",
            status_enum,
            server_default="Wanted",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("books", "p_status")
    op.drop_column("books", "a_status")
    # ### end Alembic commands ###
