"""add more fields

Revision ID: 1758f73a4ac4
Revises: aba238d9f70a
Create Date: 2025-06-25 23:01:11.434295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1758f73a4ac4'
down_revision: Union[str, None] = 'aba238d9f70a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('books', sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('books', sa.Column('editions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('series', sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'external_refs')
    op.drop_column('books', 'editions')
    op.drop_column('books', 'external_refs')
    op.drop_column('authors', 'external_refs')
    # ### end Alembic commands ###
