"""change models to new structure

Revision ID: 575705550f21
Revises: a9c2edea4d55
Create Date: 2025-06-28 04:32:55.797008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575705550f21'
down_revision: Union[str, None] = 'a9c2edea4d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.drop_constraint('books_series_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'author_id')
    op.drop_column('books', 'series_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('series_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('books_series_id_fkey', 'books', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
