"""Update author and book models

Revision ID: f94ef077a93e
Revises: 001_initial_schema
Create Date: 2025-03-29 22:25:28.909310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f94ef077a93e'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('biography', sa.String(), nullable=True))
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('books', sa.Column('description', sa.String(), nullable=True))
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('books', 'pages',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('books', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('books_user_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    op.alter_column('series', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('series', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_user_id_fkey', 'books', 'users', ['user_id'], ['id'])
    op.alter_column('books', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'pages',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'isbn',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('books', 'published_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('books', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('books', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('books', 'description')
    op.alter_column('authors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('authors', 'biography')
    # ### end Alembic commands ###
